### ISSUE TITLE
Improve Teacher assistant Stability

### ISSUE THREAD

**Issue by kithe-raker** [Bualoitech/learnliko-webapp#10]
The response from assistant AI which is integrated with LangChain, most of the time seem to provided a unpredictable and irrelevant response.

**Comment by athensclub** [comment]
I have stopped using langchain for teacher assistant and use base ChatGPT instead. I found the stability to be significantly better with the assistant answering in Thai and also not refuse to answer.

Removing langchain should also allow us to deploy Sveltekit app without error. Maybe you should try deploying now?

**Comment by kithe-raker** [comment]
Ok, Btw you can attach commit in the issue by passing `#{issue number}`. So that the related commit will be viewable in the issue

**Comment by kithe-raker** [comment]
@athensclub Successfully build and deploy on Netlify
https://staging--learnliko.netlify.app/discover

**Comment by kithe-raker** [comment]
Considered this task as finished since the deploy process is success
