### ISSUE TITLE
Make quiz answers validation flow more secure.

### ISSUE THREAD

**Issue by athensclub** [Bualoitech/learnliko-webapp#14]
The quiz validation flow might not be so secure. An Api endpoint literally give answer by quiz id. I think that we can worry about this later.

We might have to ignore these for now for the sake of demo day. Perhaps open a separate issue for later?
Also, please test the pretest system and tell me if something has gone wrong :P

_Originally posted by @athensclub in https://github.com/Bualoitech/learnliko/issues/7#issuecomment-1603251935_
            
Reading quiz also has similar problems.

**Comment by kithe-raker** [comment]
Related to #18
