### ISSUE TITLE
Implement query schema from API to Dashboard

### ISSUE THREAD

**Issue by kithe-raker** [Bualoitech/learnliko-webapp#19]
Implement API so can be display data from db in the dashboard

DOD
- [x] Overall
      - Total daily active learner data
      - Learner's average CEFR level
      - Total learner
      - Learner's leaderboard
- [x] Classroom
      - All classroom
      - Learner in each classroom
- [x] Activity
      - Learner's lesson history

**Comment by athensclub** [comment]
Still have to do the Dashboard UI. Working on it.

**Comment by kithe-raker** [comment]
<img width="854" alt="Screenshot 2566-07-06 at 20 33 27" src="https://github.com/Bualoitech/learnliko-webapp/assets/54874488/b4512bed-6fc2-486c-b262-09350dc2b4fd">
The UI on Activity page still using the old design one. I will move on to other task, and comeback implement data if the new ui is finished

**Comment by kithe-raker** [comment]
Remove query activity from trial
