### ISSUE TITLE
Improve conversation session with AI

### ISSUE THREAD

**Issue by kithe-raker** [Bualoitech/learnliko-webapp#25]
Rn, the conversation session has the following issues.
- [x] Goal checker not working properly
- [x] Score/Recap computation
- [x] Modify conversation recap data model in graphQL
- [x] Handling transcription sometime return `undefined`
- [x] Implement TTS to hint text

**Comment by kithe-raker** [comment]
Our assumption about `Goal checker` is not working properly is that
- No context provided to gpt
which may cause gpt to not be able to understand the situation in the conversation
- Model may need to fine-tune to work more efficiency

**Comment by kithe-raker** [comment]
To improve Score/Recap computation efficiency we assume that the json schema which is  provided to gpt function calling is too complex(contain many nested object), so we gonna divide it into to small object of each subject instead
.
Plus, in the current schema we instruct gpt to provide us a score in the scale of 0-100, which turn out not in the way we expected. So we decided to use enum value instead to avoid gpt's hallucination.

here the example of json schema:
```js
grammar: {
	type: 'object',
	properties: {
		         correctness: {
		                         type: 'enum',
					enum: ["BAD", "MEDIUM", "PERFECT"]
					description: `Evaluate the grammar used in the User's dialogue and determine its correctness and clarity`
				},
			examples: {
				type: 'array',
				items: {
						type: 'string'
				},
				maxItems: 3,
				description: `Provide User the examples of the response with correct grammar`
			}
		}
}
```

**Comment by kithe-raker** [comment]
Here a best practice for GPT documentation
https://platform.openai.com/docs/guides/gpt-best-practices

**Comment by kithe-raker** [comment]
@athensclub  I found this section might be useful for goal checker 
https://platform.openai.com/docs/guides/gpt-best-practices/strategy-give-gpts-time-to-think

**Comment by kithe-raker** [comment]
Useful tool that we could utilize in the future to ensure the efficiency of model and prompt:
https://github.com/openai/evals

**Comment by athensclub** [comment]
The only time that I have been able to get `undefined` from transcription is when I record and stop really quickly. The response become the following:
```js
{
  error: {
    message: "Invalid file format. Supported formats: ['m4a', 'mp3', 'webm', 'mp4', 'mpga', 'wav', 'mpeg']",
    type: 'invalid_request_error',
    param: null,
    code: null
  }
}
```
So assuming that undefined happen only when audio is to short, the transcription result of these error would return empty string for now. If you have another idea, let me know.
