### ISSUE TITLE
Content and Measurement Quailty

### ISSUE THREAD

**Issue by bualoidev** [Bualoitech/learnliko-webapp#3]
As an educational platform, we're committed to providing the highest quality content and measurements generated and analyzed by our AI. To achieve this, we rely on research, textbooks, and design techniques to train our AI while keeping costs low. We've divided our quality standards into **three categories**:

- [x]  **Content quality**: Our AI must generate accurate content that makes sense. We use textbook data to provide examples that help create new content, including high-quality translations into Thai.

- [x]  **Measurement quality**: Our AI uses clear criteria based on CEFR measurements, which can be compared to IELTS and other English language proficiency tests. We need to provide examples of words or sentences that indicate the learner's proficiency level.

- [x]  #10 
**Teacher assistant response quality**: Teacher assistants play a crucial role in helping students, especially in schools where personnel may be limited. We're working to create teacher assistants that can provide proper guidance to children and work at a level close to that of a real teacher.

- [x]  **Optimize transcribing**

**Comment by kithe-raker** [comment]
For **Teacher assistant**, Right now there is a problem with vector db which is used by Langchain to provided accurate information.
.
However @athensclub have tried switching vector db, from HNSWLib -> Faiss. But the error still occurs as 
```
f001481 ERROR  Error: Please install hnswlib-node as a dependency with, e.g. `npm install -S hnswlib-node`
    at Function.imports (file:///var/task/node_modules/langchain/dist/vectorstores/hnswlib.js:172:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function.getHierarchicalNSW (file:///var/task/node_modules/langchain/dist/vectorstores/hnswlib.js:35:37)
    at async HNSWLib.initIndex (file:///var/task/node_modules/langchain/dist/vectorstores/hnswlib.js:49:26)
    at async HNSWLib.addVectors (file:///var/task/node_modules/langchain/dist/vectorstores/hnswlib.js:68:9)
    at async Function.fromDocuments (file:///var/task/node_modules/langchain/dist/vectorstores/hnswlib.js:163:9)
    at async file:///var/task/.netlify/server/entries/endpoints/api/v1/conversation/assistant/_s
```

**Comment by kithe-raker** [comment]
**Optimize transcribing** has been solved by using alternate api(OpenAI Whisper API), which show a satisfied result in branch `whisper-transcription`. Now is merge to `develop` branch, so this topic will be consider as finished

**Comment by kithe-raker** [comment]
> For **Teacher assistant**, Right now there is a problem with vector db which is used by Langchain to provided accurate information. . However @athensclub have tried switching vector db, from HNSWLib -> Faiss. But the error still occurs as
> 
> ```
> f001481 ERROR  Error: Please install hnswlib-node as a dependency with, e.g. `npm install -S hnswlib-node`
>     at Function.imports (file:///var/task/node_modules/langchain/dist/vectorstores/hnswlib.js:172:19)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async Function.getHierarchicalNSW (file:///var/task/node_modules/langchain/dist/vectorstores/hnswlib.js:35:37)
>     at async HNSWLib.initIndex (file:///var/task/node_modules/langchain/dist/vectorstores/hnswlib.js:49:26)
>     at async HNSWLib.addVectors (file:///var/task/node_modules/langchain/dist/vectorstores/hnswlib.js:68:9)
>     at async Function.fromDocuments (file:///var/task/node_modules/langchain/dist/vectorstores/hnswlib.js:163:9)
>     at async file:///var/task/.netlify/server/entries/endpoints/api/v1/conversation/assistant/_s
> ```

This is the error after switch to Faiss
```
Jun 9, 02:26:03 PM: 370ce39b ERROR  Error: Could not import faiss-node. Please install faiss-node as a dependency with, e.g. `npm install -S faiss-node` and make sure you have `libomp` installed in your path.

Error: libgomp.so.1: cannot open shared object file: No such file or directory
    at Function.importFaiss (file:///var/task/node_modules/langchain/dist/vectorstores/faiss.js:207:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async FaissStore.addVectors (file:///var/task/node_modules/langchain/dist/vectorstores/faiss.js:60:37)
    at async Function.fromDocuments (file:///var/task/node_modules/langchain/dist/vectorstores/faiss.js:197:9)
    at async file:///var/task/.netlify/server/entries/endpoints/api/v1/conversation/assistant/_server.ts.js:17:21
```

**Comment by kithe-raker** [comment]
If we gonna keep it running on sveltekit server, it has to be able to run on Node.js, else we may have to deploy a separate server(sound like a lot of setup)
