### ISSUE TITLE
Full Version Requirements

### ISSUE THREAD

**Issue by bualoidev** [Bualoitech/learnliko-webapp#30]
**Students**

1. Lessons
[ 3 paragraphs of Stories + 3 Background Images + 1 ambient song + Can add more or dynamic activities in future  ]

     - Vocab (vocab flip card)
           - Image and Choices
           - Thai words and Choices (for adj)
     - Grammar
           - Fill in the blank
     - Reading
           - maximum 4 paragraphs
           - quizzes
     - Conversation
           - maximum 3 Goals
           - Use the difficulty level according to Lesson's CEFR
          
2. Discover Lessons
           - Suggest to continue playing
           - Suggest from CEFR Level
           
3. AI Friends
           - Unlock characters the learner has met
           - Save conversation history
           
4. Libraries
           - Daily Reading Contents
           - Can add more new topics
           
5. Friend spaces
           - Leader board
           - View friend profile
           - chatroom
           - hangbot game (single-player, multiplayer) use Learners CEFR wordlist

6. Account
           - CEFR Level calc
           - Get Certificate
           - Lesson's Recap
           - Coin and EXP
           - Daily Time spend
           - Avatar and Cover image shop
           - Daily Vocabs
           
7. Assistants
           - Grammar Correct and Explain
           - Suggest new vocab and sentences for use in real-life situations
           - Teach students to practice speaking ( give words and sound and let learner follow speak)
           - Daily Engage (notify students to finish lesson )
           - Daily Encourage Students
           
8. Platform
           - iOS and Android
           - Tablet, Mobile, Desktop

**Comment by bualoidev** [comment]
**Teachers**

Overview
- Total Students
- Daily Learners
- Daily Learning Recap Graph
- Leaderboard


Classroom

**Comment by bualoidev** [comment]
**Operating System**

- Can auto pre-gen Lesson contents
![image](https://github.com/Bualoitech/learnliko-webapp/assets/123578300/45d28452-883f-44d3-8b99-22b72571e590)

- Can auto pre-gen Reading contents

- Display other important information (BUG, etc.)

**Comment by kithe-raker** [comment]
Since the client reject buying Learnliko, this issue is no longer relevant
